apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    alertmanagerConfig: example
  name: slack-mongo
spec:
  receivers:
  - name: slack-mongo
    slackConfigs:
    - apiURL:
        key: apiURL
        name: slack-secret
        optional: false
      channel: '#monitoring-infrastructure'
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len}}{{ end }}] Monitoring Event Notification'
      text: |-
        {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
          *Description:* {{ .Annotations.description }}
          *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{.Annotations.runbook }}|:spiral_note_pad:>
          *Details:*
          {{ range .Labels.SortedPairs }} *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
          {{ end }}
  route:
    groupBy:
    - severity
    groupInterval: 60s
    groupWait: 60s
    receiver: slack-mongo
    repeatInterval: 1m
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-secret
data:
  apiURL: >
    <encoded secret goes here>
